language: cpp
#compiler: gcc
sudo: false

addons:
  apt:
    packages:
      - valgrind
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

- os: linux
   env: UNIT_TESTS=true COMPILER=g++-6     BOOST_VERSION=default ENABLE_MEMCHECK=true
      compiler: gcc
      
before_script:
  - git config --global user.name "Macrochaos"
  - git config --global user.email "andressumano@hotmail.com"
script:

gcc -Wall ArchMageEngine.sln
msbuild ArchMageEngine.sln 
devenv ArchMageEngine.sln /Build Debug

notifications:
    on_success: change
    on_failure: always